spring:
  application:
    name: PassExChange

  datasource:
    url: jdbc:mysql://localhost:3306/passexchange
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 287184763370-v7s8uhlidbpvg08mg010slllmkucs8ur.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          facebook:
            clientId: 935767661624220
            clientSecret: 38b5fb37afd767e3a00f61362b50d348
            scope:
              - email
              - public_profile

  mail:
    host: smtp.gmail.com
    port: 587
    username: thuatnhcps26351@fpt.edu.vn
    password: juwbphabqqilyofx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
